# Generated by Django 5.1.7 on 2025-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(default='Image of an amazing supercar', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='carimage',
            name='category',
            field=models.CharField(choices=[('Side View', 'Side View'), ('Doors Open', 'Doors Open'), ('Engine', 'Engine'), ('Interior', 'Interior'), ('From Behind', 'From Behind')], default='Side View', max_length=50),
        ),
    ]
