# Generated by Django 5.1.7 on 2025-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
